kind: Deployment
apiVersion: apps/v1
metadata:
  name: article-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: article-service
  template:
    metadata:
      labels:
        app: article-service
    spec:
      containers:
        - name: article-service
          image: rikp777/article-service
          imagePullPolicy: Always
          ports:
            - containerPort: 7078

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7078
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7078
            initialDelaySeconds: 5
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: article-service

spec:
  type: NodePort
  ports:
    - port: 7078
      targetPort: 7078
      protocol: TCP
      nodePort: 31000
  selector:
    app: article-service