kind: Deployment
apiVersion: apps/v1
metadata:
  name: article-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: article-service
  template:
    metadata:
      labels:
        app: article-service
    spec:
      containers:
        - name: article-service
          image: eu.gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 7078
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 100m

          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: springdatasourcedriverclassname
                  key: com.mysql.jdbc.Driver
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: springdatasourceurl
                  key: studmysql01.fhict.local
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springdatasourcepassword
                  key: Egt4gTSMOK
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: springdatasourceusername
                  key: dbi409059

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7078
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7078
            initialDelaySeconds: 5
      restartPolicy: Always