kind: Service
apiVersion: v1
metadata:
  name: article-service

spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 7078
      targetPort: 7078
  selector:
    app: article-service

  externalIPs:
    - 127.0.0.1