version: '2'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: "kafka"
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REPLICA_FETCH_MAX_BYTES: 2147483646
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2147483646
      KAFKA_MESSAGE_MAX_BYTES: 2147483646
      KAFKA_REQUEST_TIMEOUT_MS: 30000
      KAFKA_RESERVED_BROKER_MAX_ID: 1000
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  eureka-service:
    container_name: eureka-service
    build: ./eureka-service
    ports:
    - 8761:8761

  zuul-service:
    container_name: zuul-service
    build: ./zuul-service
    ports:
    - 80:80
    depends_on:
      - eureka-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka



  database:
    image: mariadb # or mysql they are basically the same
    container_name: flowcontrol_database
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

    volumes:
      - /home/rik/mariadb/flowcontrol:/var/lib/mysql

    ports:
      - 6072:3306

    networks:
      - flowcontrol-network

    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10




#Docker Networks
networks:
  flowcontrol-network:
    driver: bridge