version: '3'

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: "kafka"
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REPLICA_FETCH_MAX_BYTES: 2147483646
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2147483646
      KAFKA_MESSAGE_MAX_BYTES: 2147483646
      KAFKA_REQUEST_TIMEOUT_MS: 30000
      KAFKA_RESERVED_BROKER_MAX_ID: 1000
    depends_on:
      - zookeeper

    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --topic flow --describe" ]
      interval: 2s
      timeout: 2s
      retries: 15

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: zookeeper
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    depends_on:
      database:
        condition: service_healthy

  eureka-service:
    container_name: eureka-service
    hostname: eureka-service
    build: ./eureka-service


    mem_limit: 350m

    ports:
    - 8761:8761

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eureka-service:8761" ]
      interval: 30s
      timeout: 10s
      retries: 5

  zuul-service:
    container_name: zuul-service
    hostname: zuul-service
    build: ./zuul-service

    command: "mvn spring-boot:run -Dspring.devtools.restart.enabled=true"

    mem_limit: 350m

    ports:
    - 80:80

    depends_on:
      eureka-service:
        condition: service_started
      database:
        condition: service_healthy

    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka



  database:
    image: mariadb # or mysql they are basically the same
    container_name: flowcontrol_database
    restart: always

    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: authservice

    ports:
      - 6073:3306


    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10

  gateway-authservice:
    build: ./gateway-authservice

    ports:
      - 7070:7070

    depends_on:
      eureka-service:
        condition: service_healthy
      database:
        condition: service_healthy

    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka
      WAIT_HOSTS=database: 6073
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECTION_TIMEOUT: 30
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/authservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
