#============SERVER============
# HTTP server port



server:
  port: 7078

  # Context path of the application
  servlet:
    context-path: /api

    # Default HTTP session time out
    session:
      timeout: 15m

spring:
  jackson:
    serialization:
      fail_on_empty_beans: false
  #============JDBC============
  datasource:
    url: jdbc:mysql://localhost:3306/article?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root

  #============JPA============
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
hibernate:
  auto_quote_keyword=true:

swagger:
  host:
    url: http://localhost:7078


