#============SERVER============
# HTTP server port



server:
  port: 7078

  # Context path of the application
  servlet:
#    context-path: /api

    # Default HTTP session time out
    session:
      timeout: 15m

spring:
  application:
    name: article-service
  jackson:
    serialization:
      fail_on_empty_beans: false
  #============JDBC============
  datasource:
    url: jdbc:mariadb://localhost:3306/article
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
    password: root

  #============JPA============
  jpa:
    hibernate:
      # ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
hibernate:
  auto_quote_keyword=true:

swagger:
  host:
    url: http://localhost:7078


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  basic:
    enable: false

  jwt:
    uri: /authservice/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey