#============SERVER============
# HTTP server port



server:
  port: 7073

  # Context path of the application
  servlet:
    context-path: /api

    # Default HTTP session time out
    session:
      timeout: 15m

spring:
  application:
    name: production-service
  hateoas:
    use-hal-as-default-json-media-type: true
  jackson:
    default-property-inclusion: NON_ABSENT
  #============JDBC============
  datasource:
    url: jdbc:mariadb://localhost:3306/production
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
    password: root

  #============JPA============
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  redis:
    hostname: localhost
    port: 6379
    password: sOmE_sEcUrE_pAsS

swagger:
  host:
    url: http://localhost:7073

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

#kafka:
#  bootstrapAdress: localhost:9092
#
#  topics:
#    transport:
#      palletlabel.topic.name: palletLabel
#      shippinglabel.topic.name: shippingLabel


security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: t!1fl0wC0NtrOlS3crEt$uP3rseCreTV3ryLong