#============SERVER============
# HTTP server port

server:
  port: 7072

  # Context path of the application
  servlet:
    context-path: /transport/api

    # Default HTTP session time out
    session:
      timeout: 15m

spring:
  application:
    name: transport-service
  #============JDBC============
  datasource:
    url: jdbc:mariadb://localhost:3306/transport
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
    password: root

  #============JPA============
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


swagger:
  host:
    url: http://localhost:7072


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.address:localhost:8761}/eureka
  instance:
    prefer-ip-address: true

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: t!1fl0wC0NtrOlS3crEt$uP3rseCreTV3ryLong