#============SERVER============
# HTTP server port

server:
  port: 7072

  # Context path of the application
  servlet:
    context-path: /api

    # Default HTTP session time out
    session:
      timeout: 15m

spring:
  #============JDBC============
  datasource:
    url: jdbc:mariadb://localhost:3306/transport
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
    password: root

  #============JPA============
  jpa:
    hibernate:
      #      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


swagger:
  host:
    url: http://localhost:7072
