version: '3'

services:
  # Setup Database
  database:
    image: mariadb # or mysql they are basically the same
    container_name: flowcontrol_transport_database
    restart: always

    environment:
      MYSQL_DATABASE: transport
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'

    volumes:
      - /home/rik/mariadb/flowcontrol/transport:/var/lib/mysql

    ports:
      - 6072:3306

    networks:
      - transport-network


    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10

  # Setup Back-end
  back-end:
    build: .
    container_name: flowcontrol_transport_api

    depends_on:
      database:
        # Only start back-end when the health check of the database is oke and up and running
        condition: service_healthy

    ports:
      - 7072:7072

    environment:
      - WAIT_HOSTS=database:6072
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECTION_TIMEOUT=30
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/transport?autoReconnect=true&useSSL=false
#      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/transport?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
#      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
#      - SPRING_JPA_DATABASE=mysql

    networks:
      - transport-network


#Docker Networks
networks:
  transport-network:
    driver: bridge

