spring:
  application:
    name: gateway-service
  data:
    rest:
      basePath: /api

  cloud:
    gateway:
      routes:
        #Auth
        - id: gateway-authservice
          uri: lb://gateway-authservice
          predicates:
            - Path=/auth/api/**
        - id: auth-frontend
          uri: https://www.google.nl/search?q=login
          predicates:
            - Path=/auth/**

        #Article
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/article/api/**
        - id: article-frontend
          uri: https://www.google.nl/search?q=article
          predicates:
            - Path=/article/**

        #Farmer
        - id: farmer-service
          uri: lb://farmer-service
          predicates:
            - Path=/farmer/api/**
        - id: farmer-frontend
          uri: https://www.google.nl/search?q=farmer
          predicates:
            - Path=/farmer/**

        #Transport
        - id: transport-service
          uri: lb://transport-service
          predicates:
            - Path=/transport/api/**
        - id: transport-frontend
          uri: https://www.google.nl/search?q=transport
          predicates:
            - Path=/transport/*

        #Production
        - id: production-service
          uri: lb://production-service
          predicates:
            - Path=/production/api/**
        - id: production-frontend
          uri: https://www.google.nl/search?q=production
          predicates:
            - Path=/production/*

server:
  port: 8762


eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.address:localhost:8761}/eureka

#  instance:
#    leaseRenewalIntervalInSeconds: 5
#    hostname: ${vcap.application.uris[0]:localhost}
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: t!1fl0wC0NtrOlS3crEt$uP3rseCreTV3ryLong