spring:
  application:
    name: zuul-service


server:
  port: 8762


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

  instance:
    appname: zuul-service
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}


zuul:
  ignored-services: '*'
  routes:
    gateway-authservice:
      path: /auth/**
      service-id: gateway-authservice
      sensitive-headers: Cookie, Set-Cookie

    article:
      path: /article/**
      service-id: article-service
      sensitive-headers: Cookie, Set-Cookie

    farmer:
      path: /farmer/**
      service-id: farmer-service
      sensitive-headers: Cookie, Set-Cookie

    transport:
      path: /transport/**
      service-id: transport-service
      sensitive-headers: Cookie, Set-Cookie
  retryable: true #for devs only

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000


security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: t!1fl0wC0NtrOlS3crEt$uP3rseCreTV3ryLong