spring:
  application:
    name: zuul-service
  data:
    rest:
      basePath: /api

server:
  port: 8762


eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.address:localhost:8761}/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}


zuul:
  ignored-services: '*'
  sensitive-headers: Cookie, Set-Cookie
  routes:
    gateway-authservice:
      path: /auth/**
      service-id: gateway-authservice


    article:
      path: /article/**
      service-id: article-service
#      stripprefix: false

    farmer:
      path: /farmer/**
      service-id: farmer-service

    transport:
      path: /transport/**
      service-id: transport-service

    production:
      path: /production/**
      service-id: production-service
  retryable: true #for devs only

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: t!1fl0wC0NtrOlS3crEt$uP3rseCreTV3ryLong