#============SERVER============
server:
  # HTTP server port
  port: 7071

  # Context path of the application
  servlet:
    context-path: /farmer/api

    # Default HTTP session time out
    session:
      timeout: 15m

  # Which baseurl:port to show in response
  forward-headers-strategy: FRAMEWORK

#============Spring============
spring:
  application:
    name: farmer-service

  #============Jackson============
  jackson:
    serialization:
      fail_on_empty_beans: false
  #============JDBC============
  datasource:
    url: jdbc:mariadb://localhost:3306/farmer
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  #============JPA============
  jpa:
    hibernate:
      # ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true


#============Springdoc============
springdoc:
  swagger-ui:
    path: /docs.html


#============Eureka============
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.address:localhost:8761}/eureka
  instance:
    prefer-ip-address: true


#============Security============
security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: t!1fl0wC0NtrOlS3crEt$uP3rseCreTV3ryLong


#============Seeder============
seeder:
  debug: true
  insert-data: false