#============SERVER============
# HTTP server port



server:
  port: 7071

  # Context path of the application
  servlet:
    context-path: /api

    # Default HTTP session time out
    session:
      timeout: 15m

spring:
  jackson:
    serialization:
      fail_on_empty_beans: false
  #============JDBC============
  datasource:
    url: jdbc:mariadb://localhost:3306/farmer
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  #============JPA============
  jpa:
    hibernate:
      # ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
hibernate:
  auto_quote_keyword=true:

swagger:
  host:
    url: http://localhost:7071


