#============SERVER============
server:
  # HTTP server port
  port: 8761

#============Spring============
spring:
  application:
    name: eureka-service



#============Eureka============
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    lease:
      duration: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

#============Ribbon============
ribbon:
  ServerListRefreshInterval: 5000