#Server properties
server:
  port: 7070

  # Context path of the application
  servlet:
    context-path: /auth/api

    # Default HTTP session time out
    session:
      timeout: 15m
  forward-headers-strategy: FRAMEWORK

#Datasource properties
spring:
  application:
    name: gateway-authservice


  data:
    mariadb:
      database: authservice


  datasource:
    url: jdbc:mariadb://localhost:3386/authservice
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
    initialization-mode: always

  #JPA properties. Using ddl-auto = create will drop schema every-time.
  #Choose the correct property based on development / production role.
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  #Jackson properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        momentsUserChanged:
          destination: moments.user.changed
          contentType: application/json

#============Eureka============
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.address:localhost:8761}/eureka
  instance:
    prefer-ip-address: true


security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: t!1fl0wC0NtrOlS3crEt$uP3rseCreTV3ryLong

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33

#JWT properties
app:
  jwt:
    uri: /auth/**
    header:
      title: Authorization
      prefix: Bearer
    secret: t!1fl0wC0NtrOlS3crEt$uP3rseCreTV3ryLong
    expiration: 86400

  #Token properties
  token:
    email:
      verification:
        duration: 3600000
    password:
      reset:
        duration: 3600000
    refresh:
      duration: 3600000

  velocity:
    templates:
      location: /templates/

  #Logged out token cache
  cache:
    logoutToken:
      maxSize: 1000

#============Seeder============
seeder:
  debug: true
  insert-data: true