name: Production

on:
  push:
    branches:
      - 'master'
#    paths:
#      - 'production/**'


jobs:
  test:
    name: Test & Package
    runs-on: ubuntu-latest

    steps:
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: 'latest'
          mysql database: 'production_line'
          mysql user: 'root'
          mysql password: 'root'

      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Maven Test
        working-directory: ./production
        run: mvn -B clean test
      - name: Maven Package
        working-directory: ./production
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        working-directory: ./production
        run: mvn -B clean verify

  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
