name: Production

on:
  push:
    branches:
      - 'master'
    paths:
      - 'article/**'


jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Compile code
        working-directory: ./production
        run: mvn compile


  test:
    runs-on: ubuntu-latest
    name: Test & Package
    needs: compile

#    services:
#      mysql:
#        image: mysql:5.7
#        env:
#          MYSQL_USER: root
#          MYSQL_PASSWORD:
#          MYSQL_PORT: 3306
#          MYSQL_DATABASE: production_line
#          MYSQL_ROOT_PASSWORD: root
#        ports:
#          - 3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql database: 'article'
          mysql root password: ${{ secrets.ROOTPASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ secrets.DATABASEPASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Maven Test
        working-directory: ./production
        run: mvn -B clean test
      - name: Maven Package
        working-directory: ./production
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        working-directory: ./production
        run: mvn -B clean verify

  build:
    runs-on: ubuntu-latest
    name: Build docker image
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
