name: Production

on:
  push:
    branches:
      - 'master'
    paths:
      - 'article/**'


jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Compile code
        working-directory: ./production
        run: mvn compile


  test:
    runs-on: ubuntu-latest
    name: Test & Package
    needs: compile

    steps:
      - uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql database: 'article'
          mysql root password: ${{ secrets.ROOTPASSWORD }}
          mysql user: 'root'
          mysql password: ${{ secrets.DATABASEPASSWORD }}
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Maven Test
        working-directory: ./production
        run: mvn -B clean test
      - name: Maven Package
        working-directory: ./production
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        working-directory: ./production
        run: mvn -B clean verify

  build:
    runs-on: ubuntu-latest
    name: Build docker image
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
