name: Production

on:
  push:
    branches:
      - 'master'
#    paths:
#      - 'production/**'


jobs:
  test:
    name: Test & Package
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: production_line
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.15
      - name: Maven Test
        working-directory: ./production
        run: mvn -B clean test
      - name: Maven Package
        working-directory: ./production
        run: mvn -B clean package -DskipTests
      - name: Maven Verify
        working-directory: ./production
        run: mvn -B clean verify

  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
